#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApplication1.Resource", IsApplication=true)]

namespace AndroidApplication1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_go = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnBaseNotification = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int btnBlackWidow = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int btnCall = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btnCallHistory = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int btnChild = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int btnClickButton = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int btnConfigInstance = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int btnIDNotification = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int btnIronMan = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int btnLoad = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int btnMyButton = 2131034139;
			
			// aapt resource value: 0x7f05002c
			public const int btnRotation = 2131034156;
			
			// aapt resource value: 0x7f050001
			public const int btnSave = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int btnStartActivity = 2131034120;
			
			// aapt resource value: 0x7f05001d
			public const int btnToastImage = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int btnTranslate = 2131034135;
			
			// aapt resource value: 0x7f050022
			public const int button1 = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int button3 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int button4 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int button5 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int button6 = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int button7 = 2131034155;
			
			// aapt resource value: 0x7f050013
			public const int checkBox1 = 2131034131;
			
			// aapt resource value: 0x7f050021
			public const int checkBox2 = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int datePicker1 = 2131034151;
			
			// aapt resource value: 0x7f050016
			public const int etxtPhoneNumberText = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int imageButton1 = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int imageView1 = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout1 = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int radioButton1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int radioButton2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int radioButton3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int radioButton4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int radioButton5 = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int radioGroup1 = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int relativeLayout1 = 2131034132;
			
			// aapt resource value: 0x7f05001f
			public const int tableLayout1 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int tableRow2 = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int tableRow3 = 2131034147;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050029
			public const int textView2 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int textView3 = 2131034154;
			
			// aapt resource value: 0x7f050011
			public const int toggleButton1 = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int tvCity = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int txtMain = 2131034115;
			
			// aapt resource value: 0x7f05002d
			public const int wvCylife = 2131034157;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Isolate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LayoutAskQuestion = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutNotification = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NotificationCall = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Rotation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WebView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CallHistory = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int counterbutton_text = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int mybutton_text = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
