#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApplication1.Resource", IsApplication=true)]

namespace AndroidApplication1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int countries = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_go = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001b
			public const int btn1 = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int btnAlert = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int btnAssignText = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int btnBaseNotification = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int btnBlackWidow = 2131165190;
			
			// aapt resource value: 0x7f070023
			public const int btnCall = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int btnCallHistory = 2131165220;
			
			// aapt resource value: 0x7f070018
			public const int btnCamera = 2131165208;
			
			// aapt resource value: 0x7f070029
			public const int btnChild = 2131165225;
			
			// aapt resource value: 0x7f070027
			public const int btnClickButton = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int btnConfigInstance = 2131165221;
			
			// aapt resource value: 0x7f070009
			public const int btnIDNotification = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int btnIronMan = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int btnLoad = 2131165188;
			
			// aapt resource value: 0x7f070026
			public const int btnMyButton = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int btnReadFolder = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int btnReadInternal = 2131165214;
			
			// aapt resource value: 0x7f070037
			public const int btnRotation = 2131165239;
			
			// aapt resource value: 0x7f070003
			public const int btnSave = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int btnStartActivity = 2131165194;
			
			// aapt resource value: 0x7f070028
			public const int btnToastImage = 2131165224;
			
			// aapt resource value: 0x7f070022
			public const int btnTranslate = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int btnWriteFolder = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int btnWriteInternal = 2131165213;
			
			// aapt resource value: 0x7f07002d
			public const int button1 = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int button3 = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int button4 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int button5 = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int button6 = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int button7 = 2131165238;
			
			// aapt resource value: 0x7f070015
			public const int checkBox1 = 2131165205;
			
			// aapt resource value: 0x7f07002c
			public const int checkBox2 = 2131165228;
			
			// aapt resource value: 0x7f070032
			public const int datePicker1 = 2131165234;
			
			// aapt resource value: 0x7f070001
			public const int editTextContent = 2131165185;
			
			// aapt resource value: 0x7f070021
			public const int etxtPhoneNumberText = 2131165217;
			
			// aapt resource value: 0x7f07003b
			public const int help = 2131165243;
			
			// aapt resource value: 0x7f07000c
			public const int imageButton1 = 2131165196;
			
			// aapt resource value: 0x7f070017
			public const int imageView1 = 2131165207;
			
			// aapt resource value: 0x7f07003c
			public const int itemMenu1 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int itemMenu2 = 2131165245;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout1 = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int listView1 = 2131165210;
			
			// aapt resource value: 0x7f070039
			public const int menuMain = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int new_game = 2131165242;
			
			// aapt resource value: 0x7f07000e
			public const int radioButton1 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int radioButton2 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int radioButton3 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int radioButton4 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int radioButton5 = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int radioGroup1 = 2131165197;
			
			// aapt resource value: 0x7f07001c
			public const int relativeContainer = 2131165212;
			
			// aapt resource value: 0x7f070016
			public const int relativeLayout1 = 2131165206;
			
			// aapt resource value: 0x7f07002a
			public const int tableLayout1 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int tableRow2 = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int tableRow3 = 2131165230;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070034
			public const int textView2 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int textView3 = 2131165237;
			
			// aapt resource value: 0x7f070013
			public const int toggleButton1 = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int tvCity = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int txtMain = 2131165189;
			
			// aapt resource value: 0x7f070038
			public const int wvCylife = 2131165240;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustControlLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Isolate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutAskQuestion = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LayoutNotification = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ltCamera = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ltContentMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ltFlate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ltInternalStorage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ltOptionMenu = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ltWCF = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int NotificationCall = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Rotation = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int WebView = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int mymenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int OptionMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CallHistory = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int counterbutton_text = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int help = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int mybutton_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int new_game = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
