//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.34014。
// 
#pragma warning disable 1591

namespace AndroidApplication1.PersonnelReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPersonnelServices", Namespace="http://tempuri.org/")]
    public partial class PersonnelServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServerNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDineListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchDineOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOfficialDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOfficialDocumentAllOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonnelServices() {
            this.Url = "http://172.16.6.123/CylifeAppservice/PersonnelServices.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServerNameCompletedEventHandler ServerNameCompleted;
        
        /// <remarks/>
        public event getDineListCompletedEventHandler getDineListCompleted;
        
        /// <remarks/>
        public event SearchDineCompletedEventHandler SearchDineCompleted;
        
        /// <remarks/>
        public event SearchOfficialDocumentsCompletedEventHandler SearchOfficialDocumentsCompleted;
        
        /// <remarks/>
        public event SearchOfficialDocumentAllCompletedEventHandler SearchOfficialDocumentAllCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonnelServices/ServerName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServerName() {
            object[] results = this.Invoke("ServerName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServerNameAsync() {
            this.ServerNameAsync(null);
        }
        
        /// <remarks/>
        public void ServerNameAsync(object userState) {
            if ((this.ServerNameOperationCompleted == null)) {
                this.ServerNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServerNameOperationCompleted);
            }
            this.InvokeAsync("ServerName", new object[0], this.ServerNameOperationCompleted, userState);
        }
        
        private void OnServerNameOperationCompleted(object arg) {
            if ((this.ServerNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServerNameCompleted(this, new ServerNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonnelServices/getDineList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getDineList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EmpID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string YYMM) {
            object[] results = this.Invoke("getDineList", new object[] {
                        EmpID,
                        YYMM});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDineListAsync(string EmpID, string YYMM) {
            this.getDineListAsync(EmpID, YYMM, null);
        }
        
        /// <remarks/>
        public void getDineListAsync(string EmpID, string YYMM, object userState) {
            if ((this.getDineListOperationCompleted == null)) {
                this.getDineListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDineListOperationCompleted);
            }
            this.InvokeAsync("getDineList", new object[] {
                        EmpID,
                        YYMM}, this.getDineListOperationCompleted, userState);
        }
        
        private void OngetDineListOperationCompleted(object arg) {
            if ((this.getDineListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDineListCompleted(this, new getDineListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonnelServices/SearchDine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchDine([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EmpID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string YYYMM) {
            object[] results = this.Invoke("SearchDine", new object[] {
                        EmpID,
                        YYYMM});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchDineAsync(string EmpID, string YYYMM) {
            this.SearchDineAsync(EmpID, YYYMM, null);
        }
        
        /// <remarks/>
        public void SearchDineAsync(string EmpID, string YYYMM, object userState) {
            if ((this.SearchDineOperationCompleted == null)) {
                this.SearchDineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchDineOperationCompleted);
            }
            this.InvokeAsync("SearchDine", new object[] {
                        EmpID,
                        YYYMM}, this.SearchDineOperationCompleted, userState);
        }
        
        private void OnSearchDineOperationCompleted(object arg) {
            if ((this.SearchDineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchDineCompleted(this, new SearchDineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonnelServices/SearchOfficialDocuments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchOfficialDocuments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EmpID) {
            object[] results = this.Invoke("SearchOfficialDocuments", new object[] {
                        EmpID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchOfficialDocumentsAsync(string EmpID) {
            this.SearchOfficialDocumentsAsync(EmpID, null);
        }
        
        /// <remarks/>
        public void SearchOfficialDocumentsAsync(string EmpID, object userState) {
            if ((this.SearchOfficialDocumentsOperationCompleted == null)) {
                this.SearchOfficialDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOfficialDocumentsOperationCompleted);
            }
            this.InvokeAsync("SearchOfficialDocuments", new object[] {
                        EmpID}, this.SearchOfficialDocumentsOperationCompleted, userState);
        }
        
        private void OnSearchOfficialDocumentsOperationCompleted(object arg) {
            if ((this.SearchOfficialDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchOfficialDocumentsCompleted(this, new SearchOfficialDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPersonnelServices/SearchOfficialDocumentAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchOfficialDocumentAll([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EmpID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DeptNo) {
            object[] results = this.Invoke("SearchOfficialDocumentAll", new object[] {
                        EmpID,
                        DeptNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchOfficialDocumentAllAsync(string EmpID, string DeptNo) {
            this.SearchOfficialDocumentAllAsync(EmpID, DeptNo, null);
        }
        
        /// <remarks/>
        public void SearchOfficialDocumentAllAsync(string EmpID, string DeptNo, object userState) {
            if ((this.SearchOfficialDocumentAllOperationCompleted == null)) {
                this.SearchOfficialDocumentAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOfficialDocumentAllOperationCompleted);
            }
            this.InvokeAsync("SearchOfficialDocumentAll", new object[] {
                        EmpID,
                        DeptNo}, this.SearchOfficialDocumentAllOperationCompleted, userState);
        }
        
        private void OnSearchOfficialDocumentAllOperationCompleted(object arg) {
            if ((this.SearchOfficialDocumentAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchOfficialDocumentAllCompleted(this, new SearchOfficialDocumentAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ServerNameCompletedEventHandler(object sender, ServerNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServerNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServerNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getDineListCompletedEventHandler(object sender, getDineListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDineListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDineListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SearchDineCompletedEventHandler(object sender, SearchDineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchDineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchDineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SearchOfficialDocumentsCompletedEventHandler(object sender, SearchOfficialDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchOfficialDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchOfficialDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SearchOfficialDocumentAllCompletedEventHandler(object sender, SearchOfficialDocumentAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchOfficialDocumentAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchOfficialDocumentAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591